bugfix: add to validation for is logging in nav host (started app)
apptolast/FamilyFilmApp pull request #100
Opened 2023-11-11 00:23 UTC by gianpaul

i add a validation for is logging in the started app

2023-11-11 01:27 UTC, Coshiloco approved these changes
Looks good

2023-11-12 01:41 UTC, hgarciaalberto requested changes
Muy buen aporte, muchas gracias. 
El flujo de login mejora considerablemente, pero te he añadido un par de comentarios con algunas sugerencias.

2023-11-12 01:41 UTC, hgarciaalberto commented on app/src/main/java/com/digitalsolution/familyfilmapp/navigation/NavigationViewModel.kt
> +            send(uiState.isLogged)
La lógica de la UI en esta pantalla se gestiona mediante el objeto `NavigationUIState`, en este caso no sería necesario crear la variable `isUserLoggedIn` en `AppNavigation`.
Puedes hacer esa misma lógica utilizando la data class que se ha creado para ello: `NavigationUIState`

2023-11-12 01:41 UTC, hgarciaalberto commented on app/src/main/java/com/digitalsolution/familyfilmapp/navigation/AppNavigation.kt
> +                    .width(200.dp),
En este caso, yo mantendría el tamaño de los `CircularProgressIndicator` iguales para toda la aplicación. Sobre todo, por mantener la coherencia.

2023-11-12 01:41 UTC, hgarciaalberto commented on app/src/main/java/com/digitalsolution/familyfilmapp/navigation/AppNavigation.kt
> +            horizontalAlignment = Alignment.CenterHorizontally, // Centra el contenido horizontalmente
Este comentario, no sería necesario ya que la linea de código lo explica por si misma.

2023-11-12 01:41 UTC, hgarciaalberto commented on app/src/main/java/com/digitalsolution/familyfilmapp/navigation/AppNavigation.kt
> +            delay(800)
He probado la app sin el delay y parece mas eficiente ya que entra directamente en la la pantalla de Home. Me parece mejor User Experince que mantener al usuario casi 1 segundo viendo el CircularProgressIndicator cuando realmente no necesitamos esa espera.

2023-11-12 01:41 UTC, hgarciaalberto commented on app/src/main/java/com/digitalsolution/familyfilmapp/navigation/NavigationViewModel.kt
>      fun logOut() = firebaseAuth.signOut()
He visto que el método de `logOut` no se está usando. ¿Lo puedes borrar?

2023-11-16 23:36 UTC, hgarciaalberto commented
@gianpaul Que tal? he visto que has hecho actualizaciones pero no se si has visto el primer comentario. Si tienes alguna duda de ese cambio, lo vemos por discord.

2023-11-18 00:39 UTC, hgarciaalberto approved these changes
Awesome! Amazing job!
Well Done!
🚀

2023-11-22 00:37 UTC, merged