FFA-117 add movies to watch list and add movie for seen
apptolast/FamilyFilmApp pull request #130
Opened 2023-12-17 12:27 UTC by Coshiloco

2023-12-19 01:41 UTC, hgarciaalberto requested changes
Muy buen curro!! 👏

2023-12-19 01:41 UTC, hgarciaalberto commented on app/src/main/java/com/apptolast/familyfilmapp/ui/screens/DetailsScreen.kt
@Coshiloco Revisa los snackbar y creo que estaría!

2023-12-19 13:39 UTC, Coshiloco commented on app/src/main/java/com/apptolast/familyfilmapp/ui/screens/DetailsScreen.kt
Resuelta

2023-12-20 10:23 UTC, hgarciaalberto commented on app/src/main/java/com/apptolast/familyfilmapp/ui/screens/DetailsScreen.kt
Seguramente se puedan unificar los menajes de success en un único snackbar. Por lo demás, ok!

2023-12-20 10:24 UTC, hgarciaalberto approved these changes
Awesome job! 🚀

2023-12-20 10:24 UTC, merged