FFA-95 refactor visual cards aspects
apptolast/FamilyFilmApp pull request #97
Opened 2023-11-07 23:28 UTC by javymarmol

RecommendedCard

2023-11-08 01:52 UTC, hgarciaalberto requested changes
Mucho mejor que lo que teníamos! Gran trabajo 👏
He puesto algunos pequeños ajustes para terminar de retocar la tarea 
Muchas gracias.

2023-11-08 01:52 UTC, hgarciaalberto commented on app/src/main/java/com/digitalsolution/familyfilmapp/ui/components/RecommendedMovieCard.kt
> +    modifier: Modifier = Modifier,
@javymarmol Creo recordar que los parámetros con valores por defecto solían ponerse los últimos, o al menos, encima de las lambdas. Puedes leer mas info aqui: https://kotlinlang.org/docs/functions.html#default-arguments

2023-11-08 01:52 UTC, hgarciaalberto commented on app/src/main/java/com/digitalsolution/familyfilmapp/ui/components/RecommendedMovieCard.kt
> +                contentScale = ContentScale.FillWidth,
@javymarmol Parece que el `ContentScale.FillWidth` está cortando un poco las imágenes por arriba y por abajo. 
Habría alguna forma de dejar la imagen con un tamaño común para que se vean completas?

2023-11-08 01:52 UTC, hgarciaalberto commented on app/src/main/java/com/digitalsolution/familyfilmapp/ui/components/RecommendedMovieCard.kt
> +                    }
@javymarmol @Coshiloco @rndevelo
Una pregunta de diseño, ¿tiene sentido añadir el botón de `Read more` o que pulse directamente toda la card?

2023-11-08 01:52 UTC, hgarciaalberto commented on app/src/main/java/com/digitalsolution/familyfilmapp/ui/screens/recommend/RecommendScreen.kt
> +    navigationToDetail: () -> Unit
@javymarmol Es cierto que aun no tenemos los parámetros de navegación, pero sí sabemos que esta lambda debe contener la película que posteriormente irá como parámetro. No me parece mala idea dejarlo preparado y que la lambda sea: `(Movie) ->Unit`

2023-11-08 04:10 UTC, javymarmol commented on app/src/main/java/com/digitalsolution/familyfilmapp/ui/screens/recommend/RecommendScreen.kt
> +    navigationToDetail: () -> Unit
No han definido si va a ser por Id, o se va a pasar el objeto completo, me confirman por favor

2023-11-08 04:11 UTC, javymarmol commented on app/src/main/java/com/digitalsolution/familyfilmapp/ui/components/RecommendedMovieCard.kt
> +                    }
Fue lo que se comento, pero es totalmente válido que la acción lo tenga la card, me confirman por favor si lo dejamos en la card

2023-11-08 04:12 UTC, javymarmol commented on app/src/main/java/com/digitalsolution/familyfilmapp/ui/components/RecommendedMovieCard.kt
> +                contentScale = ContentScale.FillWidth,
Lo reviso, gracias por la anotación

2023-11-08 04:12 UTC, javymarmol commented on app/src/main/java/com/digitalsolution/familyfilmapp/ui/components/RecommendedMovieCard.kt
> +    modifier: Modifier = Modifier,
No lo tenia presente lo voy a checar

2023-11-08 13:32 UTC, foliolo commented on app/src/main/java/com/digitalsolution/familyfilmapp/ui/components/RecommendedMovieCard.kt
> +                    }
@Coshiloco me comentó que podriamos poner esa acción tanto en el boton como en la card. Pero era una pregunta, tenéis libertad para implementarlo como mejor consideréis.

2023-11-08 13:34 UTC, foliolo commented on app/src/main/java/com/digitalsolution/familyfilmapp/ui/screens/recommend/RecommendScreen.kt
> +    navigationToDetail: () -> Unit
Hay que pasar el objeto completo porque no tenía intención de realizar una petición en la screen de detalle si ya tengo toda la información de la Movie en la pantalla anterior. Lo mejor es pasarle el objeto y ahorrarnos esa comunicación con el backend. 
cc @rndevelo

2023-11-08 15:37 UTC, Coshiloco commented on app/src/main/java/com/digitalsolution/familyfilmapp/ui/components/RecommendedMovieCard.kt
> +                    }
@javymarmol asi es mi opinion con que existan esas dos posibilidades seria al forma en la que yo lo haria

2023-11-12 01:35 UTC, javymarmol commented on app/src/main/java/com/digitalsolution/familyfilmapp/ui/components/RecommendedMovieCard.kt
> +                    }
Dejo la acción en ambos

2023-11-12 01:35 UTC, javymarmol commented on app/src/main/java/com/digitalsolution/familyfilmapp/ui/screens/recommend/RecommendScreen.kt
> +    navigationToDetail: () -> Unit
vale paso el objeto completo

2023-11-18 00:11 UTC, Coshiloco approved these changes
I finish the branch Thanks for all and for your work @javymarmol

2023-11-18 00:59 UTC, hgarciaalberto approved these changes
Nice! 🚀

2023-11-18 00:59 UTC, merged